services:

  homepage:
    container_name: homepage
    environment:
      ENV: ${ENV}
    build:
      context: .
      dockerfile: Dockerfile
    image: incerto13/homepage:${ENV}-latest
    ports:
    - 8080:80